# Generated by Django 4.1.5 on 2023-02-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
